common/models/Price.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use common\models\SoldTickets;

/**
 * This is the model class for table "price".
 *
 * @property integer $id
 * @property string $name
 * @property integer $qty
 * @property string $icon
 * @property integer $eventID
 * @property float $value
 * @property float $sold
 * @property float $left
 */
class Price extends \yii\db\ActiveRecord
{
    public $iconDir = '/uploads/';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'price';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'qty', 'eventID', 'value'], 'required'],
            [['qty', 'eventID'], 'integer'],
            [['value'],'double'],
            [['name', 'icon'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'icon' => 'Иконка',
            'iconPath' => 'Иконка',
            'qty' => 'Количество',
            'value' => 'Значение',
            'eventID' => 'Событие',
            'eventName' => 'Событие',
            'companyName' => 'Компания',
            'sold' => 'Продано',
            'left' => 'Осталось',
        ];
    }

    public function getEvent()
    {
        return $this->hasOne(Event::className(),['id' => 'eventID']);
    }

    public function getCompany()
    {
        /*return $this->hasOne(Company::className(), ['eventID' => 'id'])
            ->viaTable('event', ['companyID' => 'id']);*/

        return $this->hasOne(Company::className(), ['id' => 'companyID'])
            ->viaTable('event', ['id' => 'eventID']);
    }

    public function getImage()
    {
        return $this->hasMany(Image::className(), ['id' => 'imgID'])
            ->viaTable('priceImg', ['priceID' => 'id']);
    }

    public function getEventName()
    {
        return $this->event->name;
    }

    public function getCompanyName()
    {
        return $this->event->company->name;
    }

    public function getIconPath()
    {
        if ($this->icon == null)
            return null;
        else
            return $this->iconDir.$this->icon;
    }

    public function getSold()
    {
        return SoldTickets::find()->where(['priceID' => $this->id])->count();
    }

    public function getLeft()
    {
        return $this->qty - $this->sold;
    }

    public function getNameValue()
    {
        return $this->name.' - '.$this->value.' руб. (осталось '.$this->left.')';
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Event;
use common\models\EventSearch;
use common\models\EventImg;
use common\models\Image;
use common\models\Company;
use common\models\Category;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;

/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'update', 'view', 'create', 'delete', 'photos', 'upload', 'deleteImg'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = null;
        if (isset($_GET['companyID'])){
            $model = Company::findOne($_GET['companyID']);
        }
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $categoryList = ArrayHelper::map(Category::find()->all(),'id','name');
        $companyList = ArrayHelper::map(Company::find()->all(),'id','name');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
            'categoryList' => $categoryList,
            'companyList' => $companyList,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event();
        $company = Company::find()->all();
        $category = Category::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (isset($_GET['companyID'])){
                return $this->redirect(['index', 'companyID' => $_GET['companyID']]);
            }
            else{
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'company' => $company,
                'category' => $category,
            ]);
        }
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $company = Company::find()->all();
        $category = Category::find()->all();
        $filename = null;
        if (isset($_FILES['Event']))
            if ($_FILES['Event']['error']['icon'] == 0){
                $uploadfile = '';
                $img = $_FILES['Event'];
                $uploaddir = $_SERVER['DOCUMENT_ROOT'].'frontend/web/uploads/';
                $file = pathinfo($img['name']['icon']);
                $filename = time().'.'.$file['extension'];
                $uploadfile = $uploaddir . basename($filename);
                move_uploaded_file($img['tmp_name']['icon'], $uploadfile);
            }

        if ($model->load(Yii::$app->request->post())) {
            if (isset($_FILES['Event']))
                if ($_FILES['Event']['error']['icon'] == 0)
                    $model->icon = $filename;
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else {
                echo '<pre>';
                print_r($_POST);
                echo '<pre>';
                /*return $this->render('update', [
                    'model' => $model,
                    'company' => $company,
                    'category' => $category,
                ]);*/
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'company' => $company,
                'category' => $category,
            ]);
        }
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */

    public function actionPhotos($id)
    {
        $images = EventImg::find()->where(['eventID' => $id])->joinWith('image')->all();
        $event = Event::findOne($id);
        return $this->render('photos',[
            'eventID' => $id,
            'event' => $event,
            'images' => $images,
        ]);
    }

    public function actionUpload()
    {
        if (isset($_POST) and isset($_FILES)){
            $upload_dir = '/var/www/tickets/frontend/web/uploads/';
            $filename = $_FILES['img']['name'];
            $ext = substr($filename, strpos($filename,'.'), strlen($filename)-1);
            $transaction = Image::getDb()->beginTransaction();
            try{
                $img = new Image();
                $img->name = $_FILES['img']['name'];
                //$img->size = $_FILES['img']['size'];
                $img->ext = $ext;
                $img->save();
                $imgID = $img->id;
                $eventImg = new EventImg();
                $eventImg->imgID = $imgID;
                $eventImg->eventID = $_POST['eventID'];
                $eventImg->save();
                $upload_file = $upload_dir . basename($imgID.$ext);
                move_uploaded_file($_FILES['img']['tmp_name'], $upload_file);
                $transaction->commit();
            }
            catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            } catch(\Throwable $e) {
                $transaction->rollBack();
                throw $e;
            }

        }
        return $this->renderPartial('upload');
    }

    public function actionDeleteImg()
    {
        if (isset($_POST)){
            $transaction = Image::getDb()->beginTransaction();
            try{
                $image = Image::findOne($_POST['key']);
                $file = '/var/www/tickets/frontend/web/uploads/'.$_POST['key'].$image->ext;
                EventImg::findOne(['eventID' => $_POST['eventID'], 'imgID' => $_POST['key']])->delete();
                $image->delete();
                unlink($file);
                $transaction->commit();
            }
            catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            } catch(\Throwable $e) {
                $transaction->rollBack();
                throw $e;
            }
        }
        return $this->renderPartial('deleteImg');
    }

    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/PriceController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Price;
use common\models\PriceSearch;
use common\models\Event;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * PriceController implements the CRUD actions for Price model.
 */
class PriceController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Price models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = null;
        if (isset($_GET['eventID'])){
            $model = Event::findOne($_GET['eventID']);
        }
        $searchModel = new PriceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Price model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Price model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Price();
        $event = Event::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (isset($_GET['eventID'])){
                return $this->redirect(['index', 'eventID' => $_GET['eventID']]);
            }
            else{
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'event' => $event,
            ]);
        }
    }

    /**
     * Updates an existing Price model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $event = Event::find()->all();

        $filename = null;
        if (isset($_FILES['Price']))
            if ($_FILES['Price']['error']['icon'] == 0){
                $uploadfile = '';
                $img = $_FILES['Price'];
                $uploaddir = $_SERVER['DOCUMENT_ROOT'].'frontend/web/uploads/';
                $file = pathinfo($img['name']['icon']);
                $filename = time().'.'.$file['extension'];
                $uploadfile = $uploaddir . basename($filename);
                move_uploaded_file($img['tmp_name']['icon'], $uploadfile);
            }

        if ($model->load(Yii::$app->request->post())) {
            if (isset($_FILES['Price']))
                if ($_FILES['Price']['error']['icon'] == 0)
                    $model->icon = $filename;
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'event' => $event,
            ]);
        }
    }

    /**
     * Deletes an existing Price model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Price model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Price the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Price::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/price/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model common\models\Price */
/* @var $form yii\widgets\ActiveForm */

if (isset($_GET['eventID'])){
    $model->eventID = $_GET['eventID'];
}
?>

<div class="price-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?php
    if ($model->icon != null)
        $initialPreview = ['http://'.$_SERVER['SERVER_NAME'].'/uploads/'.$model->icon];
    else
        $initialPreview = '';
    ?>
    <?= $form->field($model, 'icon')->widget(FileInput::classname(), [
        'name' => 'attachment',
        'pluginOptions' => [
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i>',
            'browseLabel' =>  'Выбрать изображение',
            'initialPreview' => $initialPreview,
            'initialPreviewAsData'=>true,
        ],
        'options' => ['accept' => 'image/*'],
    ]) ?>

    <?= $form->field($model, 'icon')->hiddenInput()->label(false); ?>

    <?= $form->field($model, 'eventID')->dropDownList(ArrayHelper::map($event,'id', 'name')) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'qty')->textInput() ?>

    <?= $form->field($model, 'value')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/price/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PriceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="price-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'qty') ?>

    <?= $form->field($model, 'eventID') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/price/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Price */

$this->title = 'Новая цена';
$this->params['breadcrumbs'][] = ['label' => 'Цены', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="price-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'event' => $event,
    ]) ?>

</div>

backend/views/price/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\PriceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Цены';
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['event/index']];
if (isset($_GET['eventID'])){
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['event/view', 'id' => $model->id]];
}
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="price-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?
        if (isset($_GET['eventID'])){
            echo Html::a('Новая цена', ['create?eventID='.$_GET['eventID']], ['class' => 'btn btn-success']);
        }
        else{
            echo Html::a('Новая цена', ['create'], ['class' => 'btn btn-success']);
        }
        ?>

    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'companyName',
            'eventName',
         //   'id',
            'name',
            'qty',
            'sold',
            'left',
            'value',
            'iconPath:image',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{list} {view} {update} {delete} ',
                'buttons' => [
                    'list' => function ($url,$model) {
                        return Html::a(
                            '<span class="glyphicon glyphicon-list"></span>',
                            '/admin/sold/index/?id='.$model->id);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/price/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Price */

$this->title = 'Редактирование цены: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Цены', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="price-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'event' => $event,
    ]) ?>

</div>

backend/views/price/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Price */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['event/index']];
$this->params['breadcrumbs'][] = ['label' => $model->event->name, 'url' => ['price/index', 'eventID' => $model->event->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="price-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить запись?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'iconPath:image',
            'name',
            'qty',
            'sold',
            'left',
            'value',
            'eventName',
        ],
    ]) ?>

</div>