common/models/Event.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "event".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $preview
 * @property string $icon
 * @property integer $companyID
 * @property integer $catID
 * @property integer $eDate
 */
class Event extends \yii\db\ActiveRecord
{
    public $iconDir = '/uploads/';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'companyID', 'catID', 'eDate', 'ageLimit'], 'required'],
            [['companyID', 'catID', 'ageLimit'], 'integer'],
            //['eDate', 'datetime', 'format' => 'yyyy-mm-dd HH:ii'],
            [['name', 'preview', 'icon', 'youtube'], 'string', 'max' => 255],
            [['description'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'description' => 'Описание',
            'preview' => 'Краткое описание',
            'icon' => 'Иконка',
            'iconPath' => 'Иконка',
            'companyID' => 'Компания',
            'catID' => 'Категория',
            'categoryName' => 'Категория',
            'companyName' => 'Компания',
            'eDate' => 'Дата',
            'ageLimit' => 'Возрастное ограничение',
            'youtube' => 'Ссылка на youtube',
        ];
    }

    public function getCompany()
    {
        return $this->hasOne(Company::className(),['id' => 'companyID']);
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(),['id' => 'catID']);
    }

    public function getImage()
    {
        return $this->hasMany(Image::className(), ['id' => 'imgID'])
            ->viaTable('eventImg', ['eventID' => 'id']);
    }

    public function getCompanyName()
    {
        return $this->company->name;
    }

    public function getCategoryName()
    {
        return $this->category->name;
    }

    public function getIconPath()
    {
        if ($this->icon == null)
            return null;
        else
            return $this->iconDir.$this->icon;
    }

    public function getPrice()
    {
        return $this->hasMany(Price::className(), ['eventID' => 'id']);
    }

    public function getPriceRange()
    {
        $min = Price::find()->where(['eventID' => $this->id])->min('value');
        $max = Price::find()->where(['eventID' => $this->id])->max('value');
        if ($min == $max)
            return "$min";
        else
            return "$min - $max";
    }

    public function getLeft()
    {
        $prices = $this->price;
        $left = 0;
        foreach($prices as $price){
            $left += SoldTickets::find()->where(['priceID' => $price->id])->count();
        }
        return Price::find()->where(['eventID' => $this->id])->sum('qty') - $left;
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Event;
use common\models\EventSearch;
use common\models\EventImg;
use common\models\Image;
use common\models\Company;
use common\models\Category;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;

/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'update', 'view', 'create', 'delete', 'photos', 'upload', 'deleteImg'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = null;
        if (isset($_GET['companyID'])){
            $model = Company::findOne($_GET['companyID']);
        }
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $categoryList = ArrayHelper::map(Category::find()->all(),'id','name');
        $companyList = ArrayHelper::map(Company::find()->all(),'id','name');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
            'categoryList' => $categoryList,
            'companyList' => $companyList,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event();
        $company = Company::find()->all();
        $category = Category::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (isset($_GET['companyID'])){
                return $this->redirect(['index', 'companyID' => $_GET['companyID']]);
            }
            else{
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'company' => $company,
                'category' => $category,
            ]);
        }
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $company = Company::find()->all();
        $category = Category::find()->all();
        $filename = null;
        if (isset($_FILES['Event']))
            if ($_FILES['Event']['error']['icon'] == 0){
                $uploadfile = '';
                $img = $_FILES['Event'];
                $uploaddir = $_SERVER['DOCUMENT_ROOT'].'frontend/web/uploads/';
                $file = pathinfo($img['name']['icon']);
                $filename = time().'.'.$file['extension'];
                $uploadfile = $uploaddir . basename($filename);
                move_uploaded_file($img['tmp_name']['icon'], $uploadfile);
            }

        if ($model->load(Yii::$app->request->post())) {
            if (isset($_FILES['Event']))
                if ($_FILES['Event']['error']['icon'] == 0)
                    $model->icon = $filename;
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else {
                echo '<pre>';
                print_r($_POST);
                echo '<pre>';
                /*return $this->render('update', [
                    'model' => $model,
                    'company' => $company,
                    'category' => $category,
                ]);*/
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'company' => $company,
                'category' => $category,
            ]);
        }
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */

    public function actionPhotos($id)
    {
        $images = EventImg::find()->where(['eventID' => $id])->joinWith('image')->all();
        $event = Event::findOne($id);
        return $this->render('photos',[
            'eventID' => $id,
            'event' => $event,
            'images' => $images,
        ]);
    }

    public function actionUpload()
    {
        if (isset($_POST) and isset($_FILES)){
            $upload_dir = '/var/www/tickets/frontend/web/uploads/';
            $filename = $_FILES['img']['name'];
            $ext = substr($filename, strpos($filename,'.'), strlen($filename)-1);
            $transaction = Image::getDb()->beginTransaction();
            try{
                $img = new Image();
                $img->name = $_FILES['img']['name'];
                //$img->size = $_FILES['img']['size'];
                $img->ext = $ext;
                $img->save();
                $imgID = $img->id;
                $eventImg = new EventImg();
                $eventImg->imgID = $imgID;
                $eventImg->eventID = $_POST['eventID'];
                $eventImg->save();
                $upload_file = $upload_dir . basename($imgID.$ext);
                move_uploaded_file($_FILES['img']['tmp_name'], $upload_file);
                $transaction->commit();
            }
            catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            } catch(\Throwable $e) {
                $transaction->rollBack();
                throw $e;
            }

        }
        return $this->renderPartial('upload');
    }

    public function actionDeleteImg()
    {
        if (isset($_POST)){
            $transaction = Image::getDb()->beginTransaction();
            try{
                $image = Image::findOne($_POST['key']);
                $file = '/var/www/tickets/frontend/web/uploads/'.$_POST['key'].$image->ext;
                EventImg::findOne(['eventID' => $_POST['eventID'], 'imgID' => $_POST['key']])->delete();
                $image->delete();
                unlink($file);
                $transaction->commit();
            }
            catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            } catch(\Throwable $e) {
                $transaction->rollBack();
                throw $e;
            }
        }
        return $this->renderPartial('deleteImg');
    }

    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/event/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use dosamigos\datetimepicker\DateTimePicker;
use dosamigos\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model common\models\Event */
/* @var $form yii\widgets\ActiveForm */

$ageLimit = [
    '0' => '0+',
    '6' => '6+',
    '12' => '12+',
    '18' => '18+',
    ];

if (isset($_GET['companyID'])){
    $model->companyID = $_GET['companyID'];
}
?>

<div class="event-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?php
    if ($model->icon != null)
        $initialPreview = ['http://'.$_SERVER['SERVER_NAME'].'/uploads/'.$model->icon];
    else
        $initialPreview = '';
    ?>
    <?= $form->field($model, 'icon')->widget(FileInput::classname(), [
        'name' => 'attachment',
        'pluginOptions' => [
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i>',
            'browseLabel' =>  'Выбрать изображение',
            'initialPreview' => $initialPreview,
            'initialPreviewAsData'=>true,
        ],
        'options' => ['accept' => 'image/*'],
    ]) ?>

    <?= $form->field($model, 'icon')->hiddenInput()->label(false); ?>

    <?= $form->field($model, 'companyID')->dropDownList(ArrayHelper::map($company,'id', 'name')) ?>

    <?= $form->field($model, 'catID')->dropDownList(ArrayHelper::map($category,'id', 'name')) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['maxlength' => true])->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'standart',
    ]) ?>

    <?= $form->field($model, 'preview')->textarea(['maxlength' => true]) ?>

    <?= $form->field($model, 'eDate')->widget(DateTimePicker::className(), [
        'language' => 'ru',
        /*'size' => 'ms',
        'template' => '{input}',*/
        'pickButtonIcon' => 'glyphicon glyphicon-time',
        //'inline' => true,
        'clientOptions' => [
            /*'startView' => 1,
            'minView' => 0,
            'maxView' => 1,*/
            'autoclose' => true,
            //'linkFormat' => 'yyyy-mm-dd HH:ii', // if inline = true
            'format' => 'yyyy-mm-dd HH:ii',
            'pickerPosition' => 'bottom-left',
        ]
    ])?>

    <?= $form->field($model, 'ageLimit')->dropDownList($ageLimit) ?>

    <?= $form->field($model, 'youtube')->textInput(['maxlength' => true]) ?>



    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?
//$this->registerJs("CKEDITOR.plugins.addExternal('pbckcode', '/js/ckeditor.js', '');");
?>

backend/views/event/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\EventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'preview') ?>

    <?= $form->field($model, 'icon') ?>

    <?php // echo $form->field($model, 'companyID') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/event/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Event */

$this->title = 'Новое событие';
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'company' => $company,
        'category' => $category,
    ]) ?>

</div>

backend/views/event/deleteImg.php
<?php
echo json_encode($_POST);

backend/views/event/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'События';
if (isset($_GET['companyID'])){
    $this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['company/view', 'id' => $model->id]];
}
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?
        if (isset($_GET['companyID'])){
            echo Html::a('Новое событие', ['create?companyID='.$_GET['companyID']], ['class' => 'btn btn-success']);
        }
        else{
            echo Html::a('Новое событие', ['create'], ['class' => 'btn btn-success']);
        }
        ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{list} {photos} {view} {update} {delete} ',
                'buttons' => [
                    'list' => function ($url,$model) {
                        return Html::a(
                            '<span class="glyphicon glyphicon-list"></span>',
                            '/admin/price/index/?eventID='.$model->id);
                    },
                    'photos' => function($action, $key, $index) {
                        return Html::a(
                            '<span class="glyphicon glyphicon-camera">',
                            Url::to(['event/photos', 'id' => $index])
                        );
                    },
                ],
            ],
            [
                'attribute'=>'companyID',
                'label'=>'Компания',
                'format'=>'text',
                'content'=>function($data){
                    return $data->companyName;
                },
                'filter' => $companyList,
            ],
            [
                'attribute'=>'catID',
                'label'=>'Категория',
                'format'=>'text',
                'content'=>function($data){
                    return $data->categoryName;
                },
                'filter' => $categoryList,
            ],
            //'id',
            'name',
            'preview',
            'description:html',
            'ageLimit',
            'eDate:datetime',
            'iconPath:image',
            'youtube',
            // 'companyID',
        ],
    ]); ?>
</div>

backend/views/event/photos.php
<?
use yii\helpers\Url;
use yii\helpers\Html;
use kartik\file\FileInput;

$this->title = $event->name.': изображения';
?>
    <h1><?= Html::encode($this->title) ?></h1>
<?
$i = 0;
$path = 'http://'.$_SERVER['SERVER_NAME'].'/uploads/';
$initialPreview = [];
$initialPreviewConfig = [];

//if ($images->count() >= 0) {
//    $images->all();
foreach ($images as $img) {
    $initialPreview[$i] = $path . $img->imgID . $img->image->ext;
    $initialPreviewConfig[$i] = [/*'caption' => $img->image->caption, 'size' => $img->image->size,*/ 'key' => $img->imgID];
    $i++;
}
//}

echo FileInput::widget([
    'name' => 'img',
    'options'=>[
        'multiple'=>true
    ],
    'pluginOptions' => [
        'allowedFileExtensions'=>['jpg', 'gif', 'png', 'bmp'],
        'initialPreview'=>$initialPreview,
        'initialPreviewAsData'=>true,
        'initialCaption'=>"Загруженное",
        'initialPreviewConfig' => $initialPreviewConfig,
        'uploadUrl' => Url::to(['/event/upload']),
        'deleteUrl' => Url::to(['/event/delete-img']),
        'uploadExtraData' => [
            'eventID' => $eventID,
        ],
        'deleteExtraData' => [
            'eventID' => $eventID,
        ],
        'maxFileCount' => 10,
        'overwriteInitial'=>false,
    ]
]);
?>

backend/views/event/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Event */

$this->title = 'Редактирование события: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="event-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'company' => $company,
        'category' => $category,
    ]) ?>

</div>

backend/views/event/upload.php
<?php
$out = json_encode($_FILES);
echo $out;

backend/views/event/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Event */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить запись?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'companyName',
            'categoryName',
//            'id',
            'icon',
            'name',
            'description:html',
            'preview',
            'ageLimit',
            'eDate:datetime',
            'iconPath:image',
            'youtube',
        ],
    ]) ?>

</div>